export const CREDENTIAL_REPOSITORY = Symbol('CREDENTIAL_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const REFRESH_TOKEN_SERVICE = Symbol('REFRESH_TOKEN_SERVICE');
export const EMAIL_SENDER = Symbol('EMAIL_SENDER');
export const PASSWORD_RESET_TOKEN_REPOSITORY = Symbol(
  'PASSWORD_RESET_TOKEN_REPOSITORY',
);
export const EMAIL_VERIFICATION_TOKEN_REPOSITORY = Symbol(
  'EMAIL_VERIFICATION_TOKEN_REPOSITORY',
);
